### ISSUE TITLE
Script issues on Mac OSX

### ISSUE THREAD

**Issue by Calavoow** [nbeaver/tengwarscript-install-guide#1]
A few issues I had on Mac 10.9.5:
- `mkdir --parents` needs to be `mkdir -p`
- `mv --verbose` needs to be `mv -v`
- wget is not installed by default (I used `brew install wget` to resolve this)
- `tar --ungzip` is not recognized.

**Comment by nbeaver** [comment]
Ok, I think I fixed them. Try it and let me know how it works.

**Comment by Calavoow** [comment]
Above issues have been resolved. However, you install to `~/texmf/` but on Mac OSX the tex live texmf folder is located at `~/Library/texmf/`.

**Comment by nbeaver** [comment]
Hm, yes, it's better to get `TEXMFHOME` from `kpsewhich`. That should also be fixed now.

**Comment by nbeaver** [comment]
Unless I hear something different, I'm going to close this issue.

**Comment by Calavoow** [comment]
Sorry for not responding, but I was unable to test this on OSX,  because I do not have a mac available anymore.

In any case, thanks for the fixes.

**Comment by nbeaver** [comment]
No problem!
