### ISSUE TITLE
Tengwar transcriber perl script

### ISSUE THREAD

**Issue by jrjhealey** [nbeaver/tengwarscript-install-guide#2]
Hi, thanks for putting this package together! Installing all this stuff otherwise is an absolute nightmare!

I was wondering if you have another copy/mirror for the perl tengwar transcriber script though as the in-text link in the repo no longer seems to work (for me at least).

Many thanks!

**Comment by jrjhealey** [comment]
Nevermind, managed to find an archived version!

**Comment by nbeaver** [comment]
Thanks for the heads-up, I linked to the Internet Archive too for the time being. If the site comes back up, I'll switch it back.

**Comment by jrjhealey** [comment]
In case the site ever ceases to be archived, I’ve also uploaded the script to a repo of my own if that’s of use/you want to link out to that too (or maybe even merge in to one repo with this one?)

https://github.com/jrjhealey/PerlTengwarTranscriber

**Comment by jrjhealey** [comment]
While I remember (maybe this belongs in a separate issue) on more recent versions of OSX, I had to edit the installer to issue `updmap` with the `—sys` flag and invoke the whole thing via `sudo`.

Just in case that’s of any use!
