### ISSUE TITLE
Changes in updmap (TeXLive 2017.20180305-1) – requires an argument

### ISSUE THREAD

**Issue by Cigydd** [nbeaver/tengwarscript-install-guide#3]
Hello @nbeaver ,
I’ve just come across an issue while running your tengwarscript install guide:
```bash
pavel@ideapad-310 ~/build/tengwarscript-install-guide $ ./install-tengwar-scripts.sh 
updmap [ERROR]: Either -sys or -user mode is required.
updmap [ERROR]: In nearly all cases you should use updmap -sys.
updmap [ERROR]: For special cases see http://tug.org/texlive/scripts-sys-user.html
```
Added the `--user` argument to the updmap call and everything went OK.

I’m using TeXLive version 2017.20180305-1 on Linux Mint 19 Tara.

If you add me to your co-workers I can pull the change to your repo.

**Comment by nbeaver** [comment]
Thanks for the heads-up. I appreciate the option for a pull request, but it was a quick fix anyway.

**Comment by Cigydd** [comment]
Thank you for the fix :+1:
